# Generated by Django 6.0.2 on 2026-03-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobby',
            old_name='requiremets',
            new_name='requirements',
        ),
    ]
