# Generated by Django 6.0.3 on 2026-04-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_rename_requiremets_hobby_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='used for the URLs', unique=True)),
                ('location', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Kirinyaga', 'Kirinyaga'), ('Kiambu', 'Kiambu'), ('Mombasa', 'Mombasa')], max_length=100)),
                ('capacity', models.IntegerField()),
                ('descripttion', models.TextField()),
                ('image', models.ImageField(upload_to='children_homes/')),
                ('website_url', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False, help_text="Check this to show on 'Urgent Needs' section")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
